module.exports.interfaceConfig = {
  번호: {
    required: false,
    type: "none",
    unique: true,
    column: "none",
    dataType: "none",
  },
  분류: {
    type: "select",
    required: true,
    checkObj: ["정보계", "빅데이터"],
    column: "source_system_lv1",
    dataType: "string",
  },
  송수신구분: {
    type: "select",
    required: true,
    checkObj: ["송신", "수신", "내부"],
    column: "source_system_lv2",
    dataType: "string",
  },
  서버: {
    type: "none",
    required: false,
    column: "host",
    dataType: "string",
  },
  업무구분: {
    type: "none",
    required: false,
    column: "if_type",
    dataType: "string",
  },
  전문번호: {
    type: "none",
    required: false,
    column: "if_no",
    dataType: "string",
  },
  인터페이스ID: {
    type: "none",
    required: true,
    unique: true,
    column: "_id", // + dataset_id
    refer: "IF.",
    dataType: "string",
  },
  인터페이스명: {
    type: "none",
    required: true,
    column: "name",
    dataType: "string",
  },
  인터페이스설명: {
    type: "none",
    required: false,
    column: "desc",
    dataType: "string",
  },
  인터페이스파일생성경로: {
    type: "none",
    required: false,
    column: "file_path",
    dataType: "string",
  },
  인터페이스파일명: {
    type: "none",
    required: false,
    column: "file_name",
    dataType: "string",
  },
  Size: {
    type: "none",
    required: false,
    column: "kb_size",
    dataType: "string",
  },
  건수: {
    type: "none",
    required: false,
    column: "data_count",
    dataType: "string",
  },
  테이블인스턴스명: {
    type: "none",
    required: false,
    column: "instance_name",
    dataType: "string",
  },
  테이블명: {
    type: "none",
    required: false,
    column: "tb_dataset_ids",
    dataType: "array",
  },
  대내외: {
    type: "select",
    required: false,
    checkObj: ["대내", "대외"],
    column: "in_out",
    dataType: "string",
  },
  대상기관명: {
    type: "none",
    required: false,
    column: "dept_name",
    dataType: "string",
  },
  "온라인/배치구분": {
    type: "none",
    required: false,
    column: "run_type",
    dataType: "string",
  },
  송신시스템명: {
    type: "none",
    required: false,
    column: "sender_name",
    dataType: "string",
  },
  송신시스템IP: {
    type: "none",
    required: false,
    column: "sender_ip",
    dataType: "string",
  },
  수신시스템명: {
    type: "none",
    required: false,
    column: "receiver_name",
    dataType: "string",
  },
  수신시스템IP: {
    type: "none",
    required: false,
    column: "receiver_ip",
    dataType: "string",
  },
  프로토콜유형송신: {
    type: "none",
    required: false,
    column: "protocol_sender",
    dataType: "string",
  },
  프로토콜유형수신: {
    type: "none",
    required: false,
    column: "protocol_receiver",
    dataType: "string",
  },
  데이터유형송신: {
    type: "none",
    required: false,
    column: "data_sender",
    dataType: "string",
  },
  데이터유형수신: {
    type: "none",
    required: false,
    column: "data_receiver",
    dataType: "string",
  },
  수행JOB명: {
    type: "none",
    required: false,
    column: "job",
    dataType: "string",
  },
  JOB수행시각: {
    type: "none",
    required: false,
    column: "job_run_time",
    dataType: "string",
  },
  "I/F필요시점": {
    type: "none",
    required: false,
    column: "if_point",
    dataType: "string",
  },
  발생주기: {
    type: "none",
    required: false,
    column: "period",
    dataType: "string",
  },
  발생회수: {
    type: "none",
    required: false,
    column: "run_count",
    dataType: "string",
  },
  시작일: {
    type: "regex",
    required: false,
    regex: /^\d{4}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])$/,
    column: "start_time",
    dataType: "string",
  },
  종료일: {
    type: "regex",
    required: false,
    regex: /^\d{4}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])$/,
    column: "emd_time",
    dataType: "string",
  },
  현업담당자: {
    required: true,
    type: "select",
    checkObj: "user",
    column:
      "first_owner_dept_id,first_owner_dept_name,first_owner_user_id,first_owner_name",
    dataType: "user",
  },
  업무담당자: {
    required: false,
    type: "select",
    checkObj: "user",
    column:
      "first_it_owner_dept_id,first_it_owner_dept_name,first_it_owner_user_id,first_it_owner_name",
    dataType: "user",
  },
  "운영/삭제구분": {
    type: "none",
    required: true,
    column: "operation_type",
    dataType: "string",
  },
  멤버스외담당자: {
    type: "none",
    required: false,
    column: "other_owner_name",
    dataType: "string",
  },
  처리방법: {
    type: "none",
    required: false,
    column: "process_method",
    dataType: "string",
  },
  비고: {
    type: "none",
    required: false,
    column: "note",
    dataType: "string",
  },
  구분자: {
    type: "none",
    required: false,
    column: "separator",
    dataType: "string",
  },
  작성일: {
    type: "regex",
    required: true,
    regex: /^\d{4}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])$/,
    column: "create_time",
    dataType: "string",
  },
  작성자: {
    type: "none",
    required: true,
    column: "create_user_name",
    dataType: "string",
  },
};
